#!/bin/bash
set -e


source ./functions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control xorg
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    ./debtemplate/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/get-template \
    > ./debian/get-template
chmod 755 ./debian/get-template

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.install \
    > ./debian/${CODENAME_SAFE}-xorg-settings.install
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.postinst \
     > ./debian/${CODENAME_SAFE}-xorg-settings.postinst
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.postinst \
    > debian/${CODENAME_SAFE}-xorg-livesettings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./template/etc/skel/fluxbox/lastwallpaper \
    > ./etc/skel/fluxbox/lastwallpaper
    cp -af templates/etc/skel/git* ./etc/skel/

grub_template xorg


exit 0
