#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control xorg
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-xorg-settings.install \
    > ./debian/${CODENAME_SAFE}-xorg-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/${CODENAME_SAFE}-xorg-settings.postinst \
     > ./debian/${CODENAME_SAFE}-xorg-settings.postinst

## template
rm -rf etc
cp -a ../template/etc .

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/etc/skel/fluxbox/lastwallpaper \
    > ./etc/skel/fluxbox/lastwallpaper


grub_template xorg


exit 0
