#!/bin/sh
# postinst script for #PACKAGE#

set -e


case "$1" in
    configure)
        ## NetworkManager ##
        cp -af /usr/share/wintersky-xorg-settings/etc/NetworkManager           /etc
        ## iwd ##
        cp -af /usr/share/wintersky-xorg-settings/etc/iwd                      /etc
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
