#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/siducer/.Xmodmap"

# Hopfully fixing a tint2 crash when the zoitechat tray-icon meets the systray
# by adding export G_SLICE=always-malloc, we will change to polybar the next time,
# now there is not enough time to do so
# export G_SLICE=always-malloc
#
# As workaround we use lxpanel, maybe later polybar, but time ...

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# tint2 &
lxpanel &
idesk &
# pasystray &
nm-applet &
diodon &
lxpolkit &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/siducer/.fluxbox/log"
